### PR TITLE
style: remove user-select: none

### PR DESCRIPTION
**Pull request by fries1234**
just, why was this here

just, no

### CODE REVIEW

**Review by SomethingGeneric — COMMENTED** [review]
did you make sure it like, works? (doesn't break anything else?) {i wouldn't know bc i borrowed the styles from tar.black}

**Comment by fries1234** [comment]
image

**Comment by fries1234** [comment]
also uh idk why the login buttons blue lol uh i just did `pip install -r requirements.txt` and `python main.py`

**Comment by fries1234** [comment]
dont wanna setup a systemd service thats too much work to test a css change

**Comment by SomethingGeneric** [comment]
`make deploy` lol what happened to the home text

**Comment by fries1234** [comment]
thats me highlighting the text

**Comment by fries1234** [comment]
image
it looks normal when its not highlighted

**Comment by SomethingGeneric** [comment]
OH LMFAO ok sweet thanks

**Review by SomethingGeneric — APPROVED** [review]

**Pull request merged**
